### ISSUE TITLE
Fix `draw` function for plots

### ISSUE THREAD

**Issue by yebai** [TuringLang/Chain.jl#6]

**Comment by trappmartin** [comment]
Saving a plot is provided by the savefig function of Plots.jl

**Comment by yebai** [comment]
Hi @trappmartin, the `draw` function has some nice features on top of `savefig`, e.g. `draw` allow a user to combine multiple types of plots into a stack and save the stack in a single PDF file. It would be nice to keep this function!

**Comment by trappmartin** [comment]
Hm, the current implementation of plot already allows you to easily stack multiple types of plots, see example in Readme. Having a more generic way of stacking Plots.jl plots after creating the plots sounds complicated as Plots.jl acts differently as Gadfly.

**Comment by yebai** [comment]
Cool.
